name: Deploy Main Site

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Скачиваем код из GitHub
        uses: actions/checkout@v4

      - name: Настраиваем Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Устанавливаем зависимости
        run: npm install

      - name: Собираем Vite проект
        run: npx vite build packages/coredefo

      - name: Настраиваем SSH-ключ для отправки
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 2.26.123.33 >> ~/.ssh/known_hosts

      - name: Копируем файлы через нативный SCP
        run: |
          scp -r packages/coredefo/dist/* root@2.26.123.33:/var/www/coredefo/main/